### PR TITLE
Implement Apollo Server on Node.js

### PR DESCRIPTION
**Pull request by benfluleck**
**Objective**
This PR implements ApolloServer on the Node application

**Description of Change**
- Refactor app.js with logic from ApolloServer
- Re-install apolloserver to fix minor issue
- Write script to start nodemon on development

Had to fix an issue with apollo-server-express found below
https://github.com/apollographql/apollo-server/issues/1296

**Quality assurance**
- Run `npm run start:dev`

**Screen Shots**
Screenshot 2019-10-06 at 3 57 13 PM

### CODE REVIEW

**Comment by vardhanapoorv** [comment]
@benfluleck I tried executing a query but that didn't work. You will need to make more changes so that resolvers can get called.

**Comment by benfluleck** [comment]
@vardhanapoorv  thanks for this, I think you should have made it clear on the ticket. I didn't want to touch any of the other files as ApolloServer would need you to define the typeDefs which is not present at the moment.

**Comment by vardhanapoorv** [comment]
@benfluleck writing that part completely is a separate issue that is created, but if you check file in resolvers folder I have written one so that after the connection is successful anyone can check it. I hope that clarifies .

**Comment by benfluleck** [comment]
sure will implement now

**Comment by benfluleck** [comment]
@vardhanapoorv I have made the changes, I had to change some things around because of ApolloServer but it works now I have updated the screenshot

**Comment by benfluleck** [comment]
@vardhanapoorv  done 😄

**Pull request merged**
