### PR TITLE
Test cases for vue/greek-mythology

### LINKED ISSUE #23: Write test cases vue/greek-mythology
Use testing framework of your choice.

### PR DESCRIPTION
**Pull request by dewstend**
Implemented Vue-Test-Utils and Jest for the Vue project.
Unit tests were implemented as follows:
For Card component:
- Should properly display the god.name and god.desc passed to it as props

For Base component:
- should import gods from the JSON properly

As of this commit, the components pass the tests.
image

Closes #23.

> Made with 💙 at @NovaHelm.

### CODE REVIEW

**Review by vardhanapoorv — APPROVED** [review]
@dewstend Looks good to me. Please add your name in contributor list if you want to and then I will merge the changes.
Follow this [issue](https://github.com/vardhanapoorv/Open-Source-Contribution-Made-Easy/issues/10).

**Comment by dewstend** [comment]
@vardhanapoorv Pushed another commit to reflect my profile on `contributors.json`.

**Comment by vardhanapoorv** [comment]
@dewstend thanks for adding it. You will need to update your branch with the latest `contributors.json` file. Since it's having conflicts and then I can merge it.

**Comment by dewstend** [comment]
@vardhanapoorv Solved the conflicts.

**Comment by vardhanapoorv** [comment]
@dewstend  merged!

**Pull request merged**
